
services:
  app:
    build: .
    container_name: node-app
    restart: always
    ports:
      - '5000:5000'
    environment:
      MONGO_URI: mongodb://admin:password@mongo:27017
      PORT: 5000
    depends_on:
      - mongo
  mongo:
    image: mongo:6.0
    restart: always
    container_name: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db


  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo


volumes:
  mongo-data:
    

