name: CI/CD Pipeline with Docker Compose

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker 
        uses: docker/setup-docker@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build app service image with Docker Compose
        run: |
          docker-compose build app
          docker tag node-app ${{ secrets.DOCKER_USERNAME }}/crud-app:latest

      - name: Push app image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/crud-app:latest

      - name: Start containers for smoke test
        run: docker-compose up -d

      - name: Smoke test app
        run: |
          sleep 10
          curl -f http://localhost:5000 || echo "App not responding"

      - name: Stop containers
        run: docker-compose down -v

